// <auto-generated />
using System;
using ICSLib.Authen.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ICSLib.Authen.Data.Migrations
{
    [DbContext(typeof(AuthenDbContext))]
    [Migration("20220510070653_initDbCr_001")]
    partial class initDbCr_001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ICSLib.Authen.Data.Entities.Gender", b =>
                {
                    b.Property<int>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GenderDesc")
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GenderName")
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("GenderId");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            GenderId = 1,
                            GenderDesc = "Nam",
                            GenderName = "Male"
                        },
                        new
                        {
                            GenderId = 2,
                            GenderDesc = "Nữ",
                            GenderName = "Female"
                        });
                });

            modelBuilder.Entity("ICSLib.Authen.Data.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Action")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Controler")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("IsShow")
                        .HasColumnType("tinyint");

                    b.Property<byte>("LevelId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("ParentRoleId")
                        .HasColumnType("int");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint");

                    b.Property<byte>("StatusId")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "",
                            ConcurrencyStamp = "8efe4468-2bf2-4943-b3d6-0718864ffd3f",
                            Controler = "",
                            Description = "Hệ thống",
                            Icon = "",
                            IsShow = (byte)1,
                            LevelId = (byte)1,
                            Name = "System",
                            NormalizedName = "System",
                            ParentRoleId = 0,
                            SortOrder = (short)1,
                            StatusId = (byte)1
                        },
                        new
                        {
                            Id = 2,
                            Action = "",
                            ConcurrencyStamp = "34409737-6e00-4ea8-82d5-7c7e9960e4f3",
                            Controler = "",
                            Description = "Phân quyền",
                            Icon = "",
                            IsShow = (byte)1,
                            LevelId = (byte)2,
                            Name = "Authorization",
                            NormalizedName = "Authorization",
                            ParentRoleId = 1,
                            SortOrder = (short)1,
                            StatusId = (byte)1
                        },
                        new
                        {
                            Id = 3,
                            Action = "Index",
                            ConcurrencyStamp = "cab0e1f1-3d2b-4aca-bf33-e5c5ffd85a78",
                            Controler = "RoleGroup",
                            Description = "Quyền hệ thống",
                            Icon = "",
                            IsShow = (byte)1,
                            LevelId = (byte)3,
                            Name = "RoleGroup-Index",
                            NormalizedName = "RoleGroup-Index",
                            ParentRoleId = 2,
                            SortOrder = (short)1,
                            StatusId = (byte)1
                        },
                        new
                        {
                            Id = 4,
                            Action = "Create",
                            ConcurrencyStamp = "008f15ba-7edb-42e9-9d88-7e71bb69e131",
                            Controler = "RoleGroup",
                            Description = "Thêm quyền",
                            Icon = "",
                            IsShow = (byte)0,
                            LevelId = (byte)4,
                            Name = "RoleGroup-Create",
                            NormalizedName = "RoleGroup-Create",
                            ParentRoleId = 3,
                            SortOrder = (short)1,
                            StatusId = (byte)1
                        },
                        new
                        {
                            Id = 5,
                            Action = "Edit",
                            ConcurrencyStamp = "4525cff9-0f1c-425d-8aad-01110538e760",
                            Controler = "RoleGroup",
                            Description = "Cập nhật quyền",
                            Icon = "",
                            IsShow = (byte)0,
                            LevelId = (byte)4,
                            Name = "RoleGroup-Edit",
                            NormalizedName = "RoleGroup-Edit",
                            ParentRoleId = 3,
                            SortOrder = (short)2,
                            StatusId = (byte)1
                        },
                        new
                        {
                            Id = 6,
                            Action = "Delete",
                            ConcurrencyStamp = "179d78b6-ea49-40d3-9236-ce298261f852",
                            Controler = "RoleGroup",
                            Description = "Xóa quyền",
                            Icon = "",
                            IsShow = (byte)0,
                            LevelId = (byte)4,
                            Name = "RoleGroup-Delete",
                            NormalizedName = "RoleGroup-Delete",
                            ParentRoleId = 3,
                            SortOrder = (short)3,
                            StatusId = (byte)1
                        },
                        new
                        {
                            Id = 7,
                            Action = "Details",
                            ConcurrencyStamp = "5a2df975-8bd1-4f97-9592-e8d3af38568e",
                            Controler = "RoleGroup",
                            Description = "Thông tin quyền",
                            Icon = "",
                            IsShow = (byte)0,
                            LevelId = (byte)4,
                            Name = "RoleGroup-Details",
                            NormalizedName = "RoleGroup-Details",
                            ParentRoleId = 3,
                            SortOrder = (short)4,
                            StatusId = (byte)1
                        },
                        new
                        {
                            Id = 8,
                            Action = "AssignRole",
                            ConcurrencyStamp = "9c4a3f25-96bd-435c-abf5-2e3b39a47de6",
                            Controler = "RoleGroup",
                            Description = "Cập nhật chức năng cho quyền",
                            Icon = "",
                            IsShow = (byte)0,
                            LevelId = (byte)4,
                            Name = "RoleGroup-AssignRole",
                            NormalizedName = "RoleGroup-AssignRole",
                            ParentRoleId = 3,
                            SortOrder = (short)5,
                            StatusId = (byte)1
                        },
                        new
                        {
                            Id = 9,
                            Action = "Index",
                            ConcurrencyStamp = "08101046-8609-462d-9898-f9c2928be0e0",
                            Controler = "Role",
                            Description = "Chức năng",
                            Icon = "",
                            IsShow = (byte)1,
                            LevelId = (byte)3,
                            Name = "Role-Index",
                            NormalizedName = "Role-Index",
                            ParentRoleId = 2,
                            SortOrder = (short)2,
                            StatusId = (byte)1
                        },
                        new
                        {
                            Id = 10,
                            Action = "Create",
                            ConcurrencyStamp = "0a7b3dd1-53fd-4744-8d51-72ef207e8f5b",
                            Controler = "Role",
                            Description = "Thêm Chức năng",
                            Icon = "",
                            IsShow = (byte)0,
                            LevelId = (byte)4,
                            Name = "Role-Create",
                            NormalizedName = "Role-Create",
                            ParentRoleId = 9,
                            SortOrder = (short)1,
                            StatusId = (byte)1
                        },
                        new
                        {
                            Id = 11,
                            Action = "Edit",
                            ConcurrencyStamp = "a1db3e06-dce4-488d-af6e-d6692716968a",
                            Controler = "Role",
                            Description = "Cập nhật Chức năng",
                            Icon = "",
                            IsShow = (byte)0,
                            LevelId = (byte)4,
                            Name = "Role-Edit",
                            NormalizedName = "Role-Edit",
                            ParentRoleId = 9,
                            SortOrder = (short)2,
                            StatusId = (byte)1
                        },
                        new
                        {
                            Id = 12,
                            Action = "Delete",
                            ConcurrencyStamp = "fbd10223-560b-4912-a921-a509b6b72c45",
                            Controler = "Role",
                            Description = "Xóa Chức năng",
                            Icon = "",
                            IsShow = (byte)0,
                            LevelId = (byte)4,
                            Name = "Role-Delete",
                            NormalizedName = "Role-Delete",
                            ParentRoleId = 9,
                            SortOrder = (short)3,
                            StatusId = (byte)1
                        },
                        new
                        {
                            Id = 13,
                            Action = "Details",
                            ConcurrencyStamp = "e3873845-63ec-41d8-b522-8e52ac74b720",
                            Controler = "Role",
                            Description = "Thông tin Chức năng",
                            Icon = "",
                            IsShow = (byte)0,
                            LevelId = (byte)4,
                            Name = "Role-Details",
                            NormalizedName = "Role-Details",
                            ParentRoleId = 9,
                            SortOrder = (short)4,
                            StatusId = (byte)1
                        },
                        new
                        {
                            Id = 14,
                            Action = "Index",
                            ConcurrencyStamp = "058fcfae-c1d5-4057-9bbc-806f920f4448",
                            Controler = "User",
                            Description = "Người dùng",
                            Icon = "",
                            IsShow = (byte)1,
                            LevelId = (byte)3,
                            Name = "User-Index",
                            NormalizedName = "User-Index",
                            ParentRoleId = 2,
                            SortOrder = (short)3,
                            StatusId = (byte)1
                        },
                        new
                        {
                            Id = 15,
                            Action = "Create",
                            ConcurrencyStamp = "3e10290f-c136-4db3-97b2-f9f26b682afe",
                            Controler = "User",
                            Description = "Thêm người dùng",
                            Icon = "",
                            IsShow = (byte)0,
                            LevelId = (byte)4,
                            Name = "User-Create",
                            NormalizedName = "User-Create",
                            ParentRoleId = 14,
                            SortOrder = (short)1,
                            StatusId = (byte)1
                        },
                        new
                        {
                            Id = 16,
                            Action = "Edit",
                            ConcurrencyStamp = "979286b0-be2a-4a22-aec6-a4f77efc5c97",
                            Controler = "User",
                            Description = "Cập nhật người dùng",
                            Icon = "",
                            IsShow = (byte)0,
                            LevelId = (byte)4,
                            Name = "User-Edit",
                            NormalizedName = "User-Edit",
                            ParentRoleId = 14,
                            SortOrder = (short)2,
                            StatusId = (byte)1
                        },
                        new
                        {
                            Id = 17,
                            Action = "Delete",
                            ConcurrencyStamp = "cf5fb946-ffa0-47f0-8f34-ea7a342b2b60",
                            Controler = "User",
                            Description = "Xóa người dùng",
                            Icon = "",
                            IsShow = (byte)0,
                            LevelId = (byte)4,
                            Name = "User-Delete",
                            NormalizedName = "User-Delete",
                            ParentRoleId = 14,
                            SortOrder = (short)3,
                            StatusId = (byte)1
                        },
                        new
                        {
                            Id = 18,
                            Action = "Details",
                            ConcurrencyStamp = "759fff41-a0ab-40df-a279-8c85f27b3d41",
                            Controler = "User",
                            Description = "Thông tin người dùng",
                            Icon = "",
                            IsShow = (byte)0,
                            LevelId = (byte)4,
                            Name = "User-Details",
                            NormalizedName = "User-Details",
                            ParentRoleId = 14,
                            SortOrder = (short)4,
                            StatusId = (byte)1
                        },
                        new
                        {
                            Id = 19,
                            Action = "AssignRoleGroup",
                            ConcurrencyStamp = "c0a72964-4f42-414d-a33a-29e68c000909",
                            Controler = "User",
                            Description = "Cấp quyền cho người dùng",
                            Icon = "",
                            IsShow = (byte)0,
                            LevelId = (byte)4,
                            Name = "User-AssignRoleGroup",
                            NormalizedName = "User-AssignRoleGroup",
                            ParentRoleId = 14,
                            SortOrder = (short)5,
                            StatusId = (byte)1
                        },
                        new
                        {
                            Id = 20,
                            Action = "AssignRoleGroup",
                            ConcurrencyStamp = "7e99c92a-c1ee-49e7-abac-e90971fe4c21",
                            Controler = "User",
                            Description = "Cấp chức năng cho người dùng",
                            Icon = "",
                            IsShow = (byte)0,
                            LevelId = (byte)4,
                            Name = "User-AssignRole",
                            NormalizedName = "User-AssignRole",
                            ParentRoleId = 14,
                            SortOrder = (short)6,
                            StatusId = (byte)1
                        });
                });

            modelBuilder.Entity("ICSLib.Authen.Data.Entities.RoleGroup", b =>
                {
                    b.Property<int>("RoleGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleGroupDesc")
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RoleGroupName")
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<byte>("StatusId")
                        .HasColumnType("tinyint");

                    b.HasKey("RoleGroupId");

                    b.ToTable("RoleGroups");

                    b.HasData(
                        new
                        {
                            RoleGroupId = 1,
                            RoleGroupDesc = "Quản trị hệ thống",
                            RoleGroupName = "System administrator",
                            SortOrder = 1,
                            StatusId = (byte)1
                        });
                });

            modelBuilder.Entity("ICSLib.Authen.Data.Entities.RoleGroupRole", b =>
                {
                    b.Property<int>("RoleGroupId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("RoleGroupId", "RoleId");

                    b.ToTable("RoleGroupRoles");

                    b.HasData(
                        new
                        {
                            RoleGroupId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            RoleGroupId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            RoleGroupId = 1,
                            RoleId = 3
                        },
                        new
                        {
                            RoleGroupId = 1,
                            RoleId = 4
                        },
                        new
                        {
                            RoleGroupId = 1,
                            RoleId = 5
                        },
                        new
                        {
                            RoleGroupId = 1,
                            RoleId = 6
                        },
                        new
                        {
                            RoleGroupId = 1,
                            RoleId = 7
                        },
                        new
                        {
                            RoleGroupId = 1,
                            RoleId = 8
                        },
                        new
                        {
                            RoleGroupId = 1,
                            RoleId = 9
                        },
                        new
                        {
                            RoleGroupId = 1,
                            RoleId = 10
                        },
                        new
                        {
                            RoleGroupId = 1,
                            RoleId = 11
                        },
                        new
                        {
                            RoleGroupId = 1,
                            RoleId = 12
                        },
                        new
                        {
                            RoleGroupId = 1,
                            RoleId = 13
                        },
                        new
                        {
                            RoleGroupId = 1,
                            RoleId = 14
                        },
                        new
                        {
                            RoleGroupId = 1,
                            RoleId = 15
                        },
                        new
                        {
                            RoleGroupId = 1,
                            RoleId = 16
                        },
                        new
                        {
                            RoleGroupId = 1,
                            RoleId = 17
                        },
                        new
                        {
                            RoleGroupId = 1,
                            RoleId = 18
                        },
                        new
                        {
                            RoleGroupId = 1,
                            RoleId = 19
                        },
                        new
                        {
                            RoleGroupId = 1,
                            RoleId = 20
                        });
                });

            modelBuilder.Entity("ICSLib.Authen.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ActiveDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Avatar")
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CrDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 5, 10, 14, 6, 52, 326, DateTimeKind.Local).AddTicks(4485));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("OAuthId")
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("OAuthName")
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(250)");

                    b.Property<byte>("UserStatusId")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ActiveDateTime = new DateTime(2022, 5, 10, 14, 6, 52, 398, DateTimeKind.Local).AddTicks(4666),
                            Address = "Hà Nội",
                            Avatar = "",
                            Comments = "",
                            ConcurrencyStamp = "0ba523d7-9b77-43df-a3b6-657bfe3b0121",
                            CrDateTime = new DateTime(2022, 5, 10, 14, 6, 52, 398, DateTimeKind.Local).AddTicks(4315),
                            DateOfBirth = new DateTime(1988, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "thew0102@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Thế",
                            FullName = "Vũ Văn Thế",
                            GenderId = 1,
                            LastName = "Vũ Văn",
                            LockoutEnabled = false,
                            NormalizedEmail = "thew0102@gmail.com",
                            NormalizedUserName = "admin",
                            OAuthId = "",
                            OAuthName = "",
                            PasswordHash = "AQAAAAEAACcQAAAAEJAyfdjqlmPNLxLnd4glxqKwM+JRZE3qHdAuXUZkdpHg0IEtqpieoQuaG3DNgJh7Nw==",
                            PhoneNumber = "0973214793",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin",
                            UserStatusId = (byte)1
                        });
                });

            modelBuilder.Entity("ICSLib.Authen.Data.Entities.UserLog", b =>
                {
                    b.Property<int>("UserLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionCode")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ActionDesc")
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("CrDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GuidTargetObjectId")
                        .HasColumnType("int");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NewData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldeData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TargetObjectId")
                        .HasColumnType("int");

                    b.Property<string>("UserFullName")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.HasKey("UserLogId");

                    b.ToTable("UserLogs");
                });

            modelBuilder.Entity("ICSLib.Authen.Data.Entities.UserRoleGroup", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleGoupId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleGoupId");

                    b.ToTable("UserRoleGoups");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleGoupId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ProviderDisplayName")
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 5
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 6
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 7
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 8
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 9
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 10
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 11
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 12
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 13
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 14
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 15
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 16
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 17
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 18
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 19
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 20
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Value")
                        .HasMaxLength(250)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("UserId");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("ICSLib.Authen.Data.Entities.User", b =>
                {
                    b.HasOne("ICSLib.Authen.Data.Entities.Gender", "Gender")
                        .WithMany("AppUsers")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("ICSLib.Authen.Data.Entities.Gender", b =>
                {
                    b.Navigation("AppUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
